MACOSX_SDK_VERSION:    # [osx]
  - "14.5"             # [osx]
c_compiler_version:    # [ppc64le or osx]
  - 11                 # [ppc64le]
  - 21                 # [osx]
cxx_compiler_version:  # [ppc64le or osx]
  - 11                 # [ppc64le]
  - 21                 # [osx]
c_compiler:            # [win]
  - vs2019             # [win]
cxx_compiler:          # [win]
  - vs2019             # [win]
